In [1]:
import torch
print(torch.__version__)

2.5.1


In [2]:
if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

CUDA is available


In [3]:
# Empty tensor 
a = torch.empty(5, 3)
print(type(a))
print(a) # tensor with uninitialized data, garbage values

<class 'torch.Tensor'>
tensor([[1.7189e+10, 1.3845e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [4]:
# Initializing a tensor with zeros
b = torch.zeros(5, 3)    
print(b) # tensor with all elements initialized to zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
c = torch.ones(2, 3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
d = torch.rand(2, 3)
print(d) # tensor with random values uniformly distributed between 0 and 1

tensor([[0.3494, 0.9494, 0.7420],
        [0.3812, 0.2327, 0.2824]])


In [7]:
d = torch.rand(2, 3)
print(d) # tensor with random values uniformly distributed between 0 and 1

tensor([[0.0118, 0.0646, 0.7472],
        [0.1649, 0.0975, 0.0077]])


In [8]:
torch.manual_seed(42)  # Set seed for reproducibility
d = torch.rand(2, 3)
print(d) # tensor with random values uniformly distributed between 0 and 1

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [9]:
torch.manual_seed(42)  # Set seed for reproducibility
d = torch.rand(2, 3)
print(d) # tensor with random values uniformly distributed between 0 and 1

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [10]:
e = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(e)  # tensor with specified values

tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
print("torch.arange: ", torch.arange(1, 10, 2))  # tensor with values from 1 to 9 with step 2

torch.arange:  tensor([1, 3, 5, 7, 9])


In [12]:
print("torch.linspace: ", torch.linspace(1, 10, 5))  # tensor with 2 values linearly spaced between 1 and 10

torch.linspace:  tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


In [13]:
print("torch.eye: ", torch.eye(4))  # identity matrix of size 10x10

torch.eye:  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [14]:
print("torch.full: ", torch.full((3, 2), 5))  # tensor filled with the value 5

torch.full:  tensor([[5, 5],
        [5, 5],
        [5, 5]])


In [15]:
s = e.shape
print("Shape of e: ", s)  # shape of the tensor e

Shape of e:  torch.Size([2, 3])


In [16]:
x = torch.zeros_like(e)
print("x: ", x)  # tensor with the same shape as e, filled with zeros

x:  tensor([[0, 0, 0],
        [0, 0, 0]])


In [17]:
print(e.dtype)  # data type of the tensor e

torch.int64


In [18]:
f = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)  # tensor with specified values and float data type
print("f.dtype: ", f.dtype)  # tensor with specified values and float data type
print(f)  # tensor with specified values

f.dtype:  torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [19]:
print(e.dtype)  #  data type of the tensor e
e = e.to(torch.float32)  # convert e to float32 data type
print("e.dtype after conversion: ", e.dtype)  # data type of the tensor e

torch.int64
e.dtype after conversion:  torch.float32


In [28]:
x = torch.ones(2, 3)  # tensor with all elements initialized to one
print(x)
print(x + 2)
print((x + 2) * 2)
print(x / 2)
print( (x * 9) // 2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[6., 6., 6.],
        [6., 6., 6.]])
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])


In [31]:
print(x + e)  # element-wise addition of tensors x and e
print(x * e)  # element-wise multiplication of tensors x and e   


tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [44]:
x = torch.tensor([[1, 12, 3], [-4, 15, 6]])
# clamp
print(x.clamp(1, 5))  # clamp values of x between 1

tensor([[1, 5, 3],
        [1, 5, 5]])


In [45]:
print(x)
print(torch.sum(x))  # sum of all elements in x
print(torch.sum(x, dim=0))  # sum along the first dimension (columns)   
print(torch.sum(x, dim=1))  # sum along the second dimension (rows)
print(torch.mean(x.float()))  # mean of all elements in x, converting to float for mean calculation
print(torch.mean(x.float(), dim=0))  # mean along the first dimension (columns)
print(torch.mean(x.float(), dim=1))  # mean along the second dimension (rows)   

print("torch.max(x):",torch.max(x))  # maximum value in x
print("torch.argmax(x):",torch.argmax(x))  # index of the maximum value in x

print(torch.max(x, dim=0))  # maximum value along the first dimension (columns) 
print("torch.max(x, dim=1):",torch.max(x, dim=1))  # maximum value along the second dimension (rows) 

print(torch.argmax(x, dim=0))  # index of the maximum value along the first dimension (columns)
print("torch.argmax(x, dim=1:",torch.argmax(x, dim=1))  # index of the maximum value along the second dimension (rows) lues in x with their inverse indices and counts
print(torch.unique(x, sorted=True))  # unique values in x, sorted


tensor([[ 1, 12,  3],
        [-4, 15,  6]])
tensor(33)
tensor([-3, 27,  9])
tensor([16, 17])
tensor(5.5000)
tensor([-1.5000, 13.5000,  4.5000])
tensor([5.3333, 5.6667])
torch.max(x): tensor(15)
torch.argmax(x): tensor(4)
torch.return_types.max(
values=tensor([ 1, 15,  6]),
indices=tensor([0, 1, 1]))
torch.max(x, dim=1): torch.return_types.max(
values=tensor([12, 15]),
indices=tensor([1, 1]))
tensor([0, 1, 1])
torch.argmax(x, dim=1: tensor([1, 1])
tensor([-4,  1,  3,  6, 12, 15])


In [50]:
print(x.dtype, "-" , x.shape)  # data type and shape of the tensor x
print(e.dtype, "-" , e.shape) 
print(x.to(dtype=torch.float32).matmul(torch.transpose(e, 0, 1)))  # matrix multiplication of x and e

torch.int64 - torch.Size([2, 3])
torch.float32 - torch.Size([2, 3])
tensor([[34., 82.],
        [44., 95.]])


In [59]:
print(torch.det(torch.rand(2, 2)))  # determinant of a 2x2 tensor filled with ones

tensor(-0.1623)


In [62]:
print(x > e) # element-wise comparison of tensors x and e

tensor([[False,  True, False],
        [False,  True, False]])


In [64]:
print(torch.relu(e))  # ReLU activation function applied to tensor e

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [66]:
x = torch.tensor([[1, 12, 3], [-4, 15, 6]])
e = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(e)
x.add_(e)  # in-place addition of tensor e to x
print(x)  # print x after in-place addition

tensor([[ 1, 12,  3],
        [-4, 15,  6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 2, 14,  6],
        [ 0, 20, 12]])


In [67]:
xc = x.clone()  # create a clone of x
print("Clone of x:", xc)  # print the cloned tensor

Clone of x: tensor([[ 2, 14,  6],
        [ 0, 20, 12]])


In [68]:
x.device

device(type='cpu')

In [ ]:
y = x.to(device=device)  # move tensor x to the specified device (CPU or GPU
y.device  # check the device of tensor y

device(type='cuda', index=0)

In [70]:
x.flatten()  # flatten the tensor x

tensor([ 2, 14,  6,  0, 20, 12])

In [71]:
b = torch.rand(2, 3, 4)
print("b.shape:", b.shape) 
b1 = b.permute(2, 0, 1)  # permute dimensions of tensor b
print("b1.shape:", b1.shape)  # print the shape of the permuted

b.shape: torch.Size([2, 3, 4])
b1.shape: torch.Size([4, 2, 3])


In [74]:
c = torch.zeros(256, 256, 3)
print("c.shape:", c.shape)  # print the shape of tensor c
d = c.unsqueeze(1)
print("d.shape:", d.shape)  # print the shape of tensor d after unsqueeze

e = d.squeeze(1)  # remove the dimension at index 1
print("e.shape:", e.shape)  # print the shape of tensor e after squeeze

c.shape: torch.Size([256, 256, 3])
d.shape: torch.Size([256, 1, 256, 3])
e.shape: torch.Size([256, 256, 3])


In [75]:
import numpy as np
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Numpy array:", np_array)  # print the numpy array    

# Convert numpy array to PyTorch tensor
torch_tensor = torch.from_numpy(np_array)   
print("Converted PyTorch tensor:", torch_tensor)  # print the converted PyTorch tensor

Numpy array: [[1 2 3]
 [4 5 6]]
Converted PyTorch tensor: tensor([[1, 2, 3],
        [4, 5, 6]])
